# CASE 1: Transmitting "H"
N: 9
p: 3
q: 64

private_key: [1, -1, 0, 1]  # Coefficients, in decreasing degree
polynomial_g: [1, 0, 0, -1]
encoding_fuzz: [1, -1, 1, -1]

message_polynomial: [0, 1, 0, 0, 1, 0, 0, 0]

# CASE 2: Transmitting "i"
#N: 9
#p: 3
#q: 64
#
#private_key: [1, -1, 0, 1]  # Coefficients, in decreasing degree
#polynomial_g: [1, 0, 0, -1]
#encoding_fuzz: [1, -1, 1, -1]
#
#message_polynomial: [0, 1, 1, 0, 1, 1, 0, 0]

# CASE 3: Exercises
#N: 8
#p: 3
#q: 64
#
#private_key: [1, 1, 1, -1, -1, 0, -1, 1]  # Coefficients, in decreasing degree
#polynomial_g: [1, 0, -1]
#encoding_fuzz: [1, -1]
#
#message_polynomial: [0, 1, 0, 1, 0, 1, 0, 1]
